export const CHANGE_THEME = '[LAYOUT] CHANGE_THEME';
export const TOGGLE_GROUP_SELECTOR = '[LAYOUT] TOGGLE_GROUP_SELECTOR';
export const RESTORING_SELECTED_GROUP = '[LAYOUT] RESTORING_SELECTED_GROUP';
export const SET_SORT_PLAYERS_BY = '[LAYOUT] SET_SORT_PLAYERS_BY';
