export const LOADING_MATCHES = '[MATCHES] LOADING_MATCHES';
export const LOADED_MATCHES = '[MATCHES] LOADED_MATCHES';
export const ERROR_LOADING_MATCHES = '[MATCHES] ERROR_LOADING_MATCHES';
export const RESET_STATE = '[MATCHES] RESET_STATE';
export const ADDING_MATCH = '[MATCHES] ADDING_MATCH';
export const ADDED_MATCH = '[MATCHES] ADDED_MATCH';
export const ERROR_ADDING_MATCH = '[MATCHES] ERROR_ADDING_MATCH';
export const CLEAR_ERROR_ADD_MATCH = '[MATCHES] CLEAR_ERROR_ADD_MATCH';
export const RESET_ADD_MATCH_STATE = '[MATCHES] RESET_ADD_MATCH_STATE';
export const DELETING_MATCH = '[MATCHES] DELETING_MATCH';
export const DELETED_MATCH = '[MATCHES] DELETED_MATCH';
export const ERROR_DELETING_MATCH = '[MATCHES] ERROR_DELETING_MATCH';
export const CLEAR_ERROR_DELETE_MATCH = '[MATCHES] CLEAR_ERROR_DELETE_MATCH';
export const RESET_DELETE_MATCH_STATE = '[MATCHES] RESET_DELETE_MATCH_STATE';
export const LOADING_MATCH = '[MATCHES] LOADING_MATCH';
export const LOADED_MATCH = '[MATCHES] LOADED_MATCH';
export const ERROR_LOADING_MATCH = '[MATCHES] ERROR_LOADING_MATCH';
export const CLEAR_ERROR_LOAD_MATCH = '[MATCHES] CLEAR_ERROR_LOAD_MATCH';
export const RESET_LOAD_MATCH_STATE = '[MATCHES] RESET_LOAD_MATCH_STATE';
export const SUBSCRIBING = '[MATCHES] SUBSCRIBING';
export const SUBSCRIBED = '[MATCHES] SUBSCRIBED';
export const ERROR_SUBSCRIBING = '[MATCHES] ERROR_SUBSCRIBING';
export const CLEAR_SUBSCRIBE_ERROR = '[MATCHES] CLEAR_SUBSCRIBE_ERROR';
export const RESET_SUBSCRIBE_STATE = '[MATCHES] RESET_SUBSCRIBE_STATE';
export const UNSUBSCRIBING = '[MATCHES] UNSUBSCRIBING';
export const UNSUBSCRIBED = '[MATCHES] UNSUBSCRIBED';
export const ERROR_UNSUBSCRIBING = '[MATCHES] ERROR_UNSUBSCRIBING';
export const CLEAR_UNSUBSCRIBE_ERROR = '[MATCHES] CLEAR_UNSUBSCRIBE_ERROR';
export const RESET_UNSUBSCRIBE_STATE = '[MATCHES] RESET_UNSUBSCRIBE_STATE';
export const EDITING_MATCH = '[MATCHES] EDITING_MATCH';
export const EDITED_MATCH = '[MATCHES] EDITED_MATCH';
export const ERROR_EDITING_MATCH = '[MATCHES] ERROR_EDITING_MATCH';
export const CLEAR_ERROR_EDIT_MATCH = '[MATCHES] CLEAR_ERROR_EDIT_MATCH';
export const RESET_EDIT_MATCH_STATE = '[MATCHES] RESET_EDIT_MATCH_STATE';

export const EDITING_SCORE_MATCH = '[MATCHES] EDITING_SCORE_MATCH';
export const EDITED_SCORE_MATCH = '[MATCHES] EDITED_SCORE_MATCH';
export const ERROR_EDITING_SCORE_MATCH = '[MATCHES] ERROR_EDITING_SCORE_MATCH';
export const CLEAR_ERROR_EDIT_SCORE_MATCH =
  '[MATCHES] CLEAR_ERROR_EDIT_SCORE_MATCH';
export const RESET_EDIT_SCORE_MATCH_STATE =
  '[MATCHES] RESET_EDIT_SCORE_MATCH_STATE';

export const EDITING_TEAMS_MATCH = '[MATCHES] EDITING_TEAMS_MATCH';
export const EDITED_TEAMS_MATCH = '[MATCHES] EDITED_TEAMS_MATCH';
export const ERROR_EDITING_TEAMS_MATCH = '[MATCHES] ERROR_EDITING_TEAMS_MATCH';
export const CLEAR_ERROR_EDIT_TEAMS_MATCH =
  '[MATCHES] CLEAR_ERROR_EDIT_TEAMS_MATCH';
export const RESET_EDIT_TEAMS_MATCH_STATE =
  '[MATCHES] RESET_EDIT_TEAMS_MATCH_STATE';
