export const ERROR_LOADING_PLAYERS = '[PLAYERS] ERROR_LOADING_PLAYERS';
export const LOADING_PLAYERS = '[PLAYERS] LOADING_PLAYERS';
export const LOADED_PLAYERS = '[PLAYERS] LOADED_PLAYERS';
export const RESET_PLAYERS_STATE = '[PLAYERS] RESET_PLAYERS_STATE';
export const LOADING_PLAYER = '[PLAYERS] LOADING_PLAYER';
export const LOADED_PLAYER = '[PLAYERS] LOADED_PLAYER';
export const KICKING_OUT_PLAYER = '[PLAYERS] KICKING_OUT_PLAYER';
export const ERROR_KICKING_OUT_PLAYER = '[PLAYERS] ERROR_KICKING_OUT_PLAYER';
export const KICKED_OUT_PLAYER = '[PLAYERS] KICKED_OUT_PLAYER';
export const KICK_OUT_CLEAR_ERROR = '[PLAYERS] KICK_OUT_CLEAR_ERROR';
export const KICK_OUT_RESET_STATE = '[PLAYERS] KICK_OUT_RESET_STATE';
export const ERROR_LOADING_PLAYER = '[PLAYERS] ERROR_LOADING_PLAYER';
export const UPDATING_SETTINGS = '[PLAYERS] UPDATING_SETTINGS';
export const ERROR_UPDATING_SETTINGS = '[PLAYERS] ERROR_UPDATING_SETTINGS';
export const UPDATED_SETTINGS = '[PLAYERS] UPDATED_SETTINGS';
export const UPDATE_SETTINGS_CLEAR_ERROR =
  '[PLAYERS] UPDATE_SETTINGS_CLEAR_ERROR';
export const UPDATE_SETTINGS_RESET_STATE =
  '[PLAYERS] UPDATE_SETTINGS_RESET_STATE';
