export const UPDATED_PROFILE = '[PROFILE] UPDATED_PROFILE';
export const UPDATING_PROFILE = '[PROFILE] UPDATING_PROFILE';
export const CLEAR_ERROR_UPDATING_PROFILE =
  '[PROFILE] CLEAR_ERROR_UPDATING_PROFILE';
export const ERROR_UPDATING_PROFILE = '[PROFILE] ERROR_UPDATING_PROFILE';
export const ERROR_UPDATING_PASSWORD = '[PROFILE] ERROR_UPDATING_PASSWORD';
export const UPDATED_PASSWORD = '[PROFILE] UPDATED_PASSWORD';
export const UPDATING_PASSWORD = '[PROFILE] UPDATING_PASSWORD';
export const RESET_PROFILE_STATE = '[PROFILE] RESET_PROFILE_STATE';
export const UPLOADING_PROFILE_PICTURE = '[PROFILE] UPLOADING_PROFILE_PICTURE';
export const CLEAR_ERROR_UPDATING_PASSWORD =
  '[PROFILE] CLEAR_ERROR_UPDATING_PASSWORD';
